az-configuration:
{{range .azs}}
- name: {{.}}
{{end}}
properties-configuration:
  director_configuration:
    ntp_servers_string: 169.254.169.123
{{if index . "terraforming_ca_cert"}}
  security_configuration:
    trusted_certificates: |
{{indent 6 .terraforming_ca_cert}}
{{end}}
  iaas_configuration:
    access_key_id: {{.ops_manager_iam_user_access_key}}
    secret_access_key: {{.ops_manager_iam_user_secret_key}}
    iam_instance_profile: {{.ops_manager_iam_instance_profile_name}}
    vpc_id: {{.vpc_id}}
    security_group: {{.vms_security_group_id}}
    key_pair_name: {{.ops_manager_ssh_public_key_name}}
    ssh_private_key: {{ toJson .ops_manager_ssh_private_key }}
    region: {{.region}}
network-assignment:
  network:
    name: ops-manager
  singleton_availability_zone:
    name: {{index .azs 0}}
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: ops-manager
    subnets:
    {{range $i, $a := .infrastructure_subnet_cidrs}}
    - availability_zone_names:
      - {{index $.azs $i}}
      cidr: {{index $.infrastructure_subnet_cidrs $i}}
      dns: 169.254.169.253
      gateway: {{index $.infrastructure_subnet_gateways $i}}
      iaas_identifier: {{index $.infrastructure_subnet_ids $i}}
      reserved_ip_ranges: {{cidrhost (index $.infrastructure_subnet_cidrs $i) 0}}-{{cidrhost (index $.infrastructure_subnet_cidrs $i) 4}}
    {{end}}
{{if index . "pas_subnet_cidrs"}}
  - name: pas
    subnets:
    {{range $i, $a := .pas_subnet_cidrs}}
    - availability_zone_names:
      - {{index $.azs $i}}
      cidr: {{index $.pas_subnet_cidrs $i}}
      dns: 169.254.169.253
      gateway: {{index $.pas_subnet_gateways $i}}
      iaas_identifier: {{index $.pas_subnet_ids $i}}
      reserved_ip_ranges: {{cidrhost (index $.pas_subnet_cidrs $i) 0}}-{{cidrhost (index $.pas_subnet_cidrs $i) 4}}
    {{end}}
{{end}}
{{if index . "pks_subnet_cidrs"}}
  - name: pks
    subnets:
    {{range $i, $a := .pks_subnet_cidrs}}
    - availability_zone_names:
      - {{index $.azs $i}}
      cidr: {{index $.pks_subnet_cidrs $i}}
      dns: 169.254.169.253
      gateway: {{index $.pks_subnet_gateways $i}}
      iaas_identifier: {{index $.pks_subnet_ids $i}}
      reserved_ip_ranges: {{cidrhost (index $.pks_subnet_cidrs $i) 0}}-{{cidrhost (index $.pks_subnet_cidrs $i) 4}}
    {{end}}
{{end}}
{{if index . "control_plane_subnet_cidrs" }}
  - name: control-plane
    subnets:
    {{range $i, $a := .control_plane_subnet_cidrs}}
    - availability_zone_names:
        - {{index $.azs $i}}
      cidr: {{index $.control_plane_subnet_cidrs $i}}
      dns: 169.254.169.253
      gateway: {{index $.control_plane_subnet_gateways $i}}
      iaas_identifier: {{index $.control_plane_subnet_ids $i}}
      reserved_ip_ranges: {{cidrhost (index $.control_plane_subnet_cidrs $i) 0}}-{{cidrhost (index $.control_plane_subnet_cidrs $i) 4}}
    {{end}}
{{else}}
  - name: services
    subnets:
    {{range $i, $a := .services_subnet_cidrs}}
    - availability_zone_names:
        - {{index $.azs $i}}
      cidr: {{index $.services_subnet_cidrs $i}}
      dns: 169.254.169.253
      gateway: {{index $.services_subnet_gateways $i}}
      iaas_identifier: {{index $.services_subnet_ids $i}}
      reserved_ip_ranges: {{cidrhost (index $.services_subnet_cidrs $i) 0}}-{{cidrhost (index $.services_subnet_cidrs $i) 4}}
    {{end}}
{{end}}
resource-configuration:
  compilation:
    instance_type:
      id: c4.xlarge
